using Npgsql;

internal static class PostgreSqlUpgradeEvidenceSchema
{
    public static async ValueTask CreateAsync(
        UpgradeSettings settings,
        CancellationToken cancellationToken)
    {
        const string sql = """
            CREATE TABLE "UpgradeProbeEffects"
            (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OperationId" uuid NOT NULL,
                "MessageState" character varying(32) NOT NULL,
                "WorkerId" character varying(256) NOT NULL,
                "RecordedAtUtc" timestamp with time zone NOT NULL
            );
            """;

        await using var connection = new NpgsqlConnection(settings.ConnectionString);
        await connection.OpenAsync(cancellationToken);
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}
