using Npgsql;

namespace TinyEvents.Dogfood.Operations;

internal static class PostgreSqlDogfoodDatabaseReset
{
    public static async ValueTask ExecuteAsync(
        DogfoodSettings settings,
        CancellationToken cancellationToken)
    {
        await RecreateDatabaseAsync(settings, cancellationToken);
        await CreateDogfoodTablesAsync(settings, cancellationToken);
    }

    private static async ValueTask RecreateDatabaseAsync(
        DogfoodSettings settings,
        CancellationToken cancellationToken)
    {
        await using var connection = new NpgsqlConnection(
            settings.AdministrationConnectionString);
        await connection.OpenAsync(cancellationToken);
        await TerminateDatabaseConnectionsAsync(
            connection,
            settings.DatabaseName,
            cancellationToken);

        var quotedDatabaseName =
            new NpgsqlCommandBuilder().QuoteIdentifier(settings.DatabaseName);
        await ExecuteAsync(
            connection,
            $"DROP DATABASE IF EXISTS {quotedDatabaseName};",
            cancellationToken);
        await ExecuteAsync(
            connection,
            $"CREATE DATABASE {quotedDatabaseName};",
            cancellationToken);
    }

    private static async ValueTask TerminateDatabaseConnectionsAsync(
        NpgsqlConnection connection,
        string databaseName,
        CancellationToken cancellationToken)
    {
        const string sql = """
            SELECT pg_terminate_backend(pid)
            FROM pg_stat_activity
            WHERE datname = @DatabaseName
              AND pid <> pg_backend_pid();
            """;

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("DatabaseName", databaseName);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private static async ValueTask CreateDogfoodTablesAsync(
        DogfoodSettings settings,
        CancellationToken cancellationToken)
    {
        const string sql = """
            CREATE TABLE "DogfoodBusinessOperations"
            (
                "Id" uuid NOT NULL PRIMARY KEY,
                "ScenarioId" character varying(32) NOT NULL,
                "CreatedAtUtc" timestamp with time zone NOT NULL
            );

            CREATE TABLE "DogfoodEffects"
            (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OperationId" uuid NOT NULL,
                "ScenarioId" character varying(32) NOT NULL,
                "WorkerId" character varying(256) NOT NULL,
                "ProcessId" integer NOT NULL,
                "RecordedAtUtc" timestamp with time zone NOT NULL
            );

            CREATE INDEX "IX_DogfoodEffects_OperationId"
                ON "DogfoodEffects" ("OperationId");

            CREATE TABLE "DogfoodConsumerAttempts"
            (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "OperationId" uuid NOT NULL,
                "ScenarioId" character varying(32) NOT NULL,
                "WorkerId" character varying(256) NOT NULL,
                "RecordedAtUtc" timestamp with time zone NOT NULL
            );

            CREATE INDEX "IX_DogfoodConsumerAttempts_OperationId"
                ON "DogfoodConsumerAttempts" ("OperationId");
            """;

        await using var connection = new NpgsqlConnection(settings.ConnectionString);
        await connection.OpenAsync(cancellationToken);
        await ExecuteAsync(connection, sql, cancellationToken);
    }

    private static async ValueTask ExecuteAsync(
        NpgsqlConnection connection,
        string sql,
        CancellationToken cancellationToken)
    {
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }
}
