<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\TinyEvents\src\TinyEvents\TinyEvents.csproj" />
    <ProjectReference Include="..\..\..\TinyEvents\src\TinyEvents.SourceGen\TinyEvents.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>
</Project>
